config/routes.rb
Rails.application.routes.draw do
  root to: 'tops#index' 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :users, only: [:show] do
    collection do
      post :confirm
    end
    member do
        post 'review'
        get 'review'
    end
  end
  get 'users/review', to: 'users#review'
  get 'exams/show'
  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

  resources :users, :only => [:show]
  resources :reviews, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :review_users, through: :reviews, source: :user  
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :exam
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable
  has_many :exams
  has_many :reviews, dependent: :destroy
  has_many :review_exams, through: :reviews, source: :exam
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  
  def show
    @exam = Exam.offset( rand(Exam.count) ).first
    @review = current_user.reviews.find_by(exam_id: @exam.id)
  end

  def review
    @review = current_user.reviews.find_by(exam_id: @exam.id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    review = current_user.reviews.create(exam_id: params[:exam_id])
    redirect_to exams_show_url, notice: "不正解問題に登録しました"
  end
    
  def destroy
    review = current_user.reviews.find_by(id: params[:id]).destroy
    redirect_to exams_show_url, notice: "不正解問題から解除しました"
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end
  
  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit]
  before_action :edit_user, only: [:show, :edit]

  def show
    @user = User.find(params[:id])
  end
  
  def edit
  end

  def review
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "review",
        layout: 'pdf.html',
        encording: 'UTF-8',
        orientation: 'Landscape'
      end
    end
    @user = User.find(params[:id])
    @reviews_exams = @user.reviews
  end
  
  private

  def set_user
    @user = User.find(params[:id])
  end
  
  def edit_user
    unless @user.id == current_user.id
      redirect_to root_path, notice: "ユーザー本人以外は閲覧・編集できません！！"
    end 
  end 

end

app/views/exams/show.html.erb
<h1>過去問出題</h1>
<p>過去問は出題年度、分野を問わずランダムに出題されます。</p>
<p>「不正解問題に登録する」ボタンを押すとマイページの「不正解問題一覧」に記録されます。</p>
<br><br>

<h3>出題年度：<%= @exam.year %>年</h3>
<br><br>

<h3>分野名：<%= @exam.law %></h3>
<br><br>

<h3>問題：</h3>
<h3><%= @exam.question %></h3>    
<br><br>
          
<div id="output"></div>
<br><br>
<script language="javascript" type="text/javascript">
  function OnButtonClick() {
    target = document.getElementById("output");
    target.innerHTML = "<h3>解答：</h3><h3><%= @exam.answer %></h3>";
  }
  
</script>
<input type="button" value="解答を見る" onclick="OnButtonClick();"/><br />
<br />
 
    <% if @review.present? %>
      <%= button_to '不正解問題から削除する', review_path(id: @review.id), method: :delete, class: 'btn btn-danger', data: { disable_with: "削除中..." }  %><br />
    <% else %>
      <%= button_to '不正解問題に登録する', reviews_path(exam_id: @exam.id), method: :post, class: 'btn btn-primary', data: { disable_with: "登録中..." } %><br />
    <% end %>

<div class= "margin">
  <input type="button" onclick="location.href='/exams/show'"value="次の問題へ">
</div>



          

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GraduateExam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body topmargin="0">
    <header>
      <ul class="header">
        <li><a href="/">ホーム</a></li>
        <li><a href="/exams/show">過去問出題</a></li>
        <li><a href="/admin/login">管理者用ページ</a></li>
      </ul>
    </header>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    
    <% if user_signed_in? %>
    　<%= link_to "マイページ", user_path(current_user.id) %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "ログイン", new_user_session_path, class: 'post' %>
      <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
    <% end %>
    <%= yield %>
    <footer>
      <p>DIVE INTO CODE　2018年８月期　K.Sato</p>
    </footer>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>不正解問題一覧</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <%= wicked_pdf_stylesheet_link_tag    'application', 'data-turbolinks-track': 'reload' %>
    <%= wicked_pdf_javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= yield %>

  </body>
</html>

app/views/tops/index.html.erb
<h1>海事代理士試験口述試験対策アプリ</h1>
<div>
  <%= image_tag "umi.jpg" ,class: "image" %>
</div>

<div class="margin">
  <p>本サイトは海事代理士試験口述試験の過去問を学習できるアプリです。</p>
</div>

app/views/users/review.html.erb
<h1>不正解問題一覧</h1>

<table>
  <tr>
    <th>出題年度</th>
    <th>分野名</th>
    <th>問題</th>
    <th>解答</th>
  </tr>
  <% @user.review_exams.each do |exam| %>
  <tr>
    <td><%= exam.year %></td>
    <td><%= exam.law %></td>
    <td><%= exam.question %></td>
    <td><%= exam.answer %></td>
  </tr>
  <% end %>
</table>

<input type="button" onclick="location.href='/'"value="ホーム"><br />
<br />

<div class= "margin">
  <%= button_to 'PDF出力', review_user_path(@user, format: :pdf), class: %i[btn btn-default], target: '_blank' %>
</div>

app/views/users/review.pdf.erb
<h1>不正解問題一覧</h1>

<table>
  <tr>
    <th>出題年度</th>
    <th>分野名</th>
    <th>問題</th>
    <th>解答</th>
  </tr>
    <% @user = User.find(params[:id]) %>
    <% @user.review_exams.each do |exam| %>
  <tr>
    <td><%= exam.year %></td>
    <td><%= exam.law %></td>
    <td><%= exam.question %></td>
    <td><%= exam.answer %></td>
  </tr>
    <% end %>
</table>

app/views/users/show.html.erb
<h1>マイページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<% if user_signed_in? %>
  <input type="button" onclick="location.href='/users/edit'"value="編集"><br />
<% end %><br />
  <%= button_to "不正解問題一覧", review_user_path(@user.id) %><br />

<div class= "margin">
  <input type="button" onclick="location.href='/'"value="ホーム">
</div>